CREATE DOMAIN dm_role AS VARCHAR(20)
CHECK (VALUE IN ('PACIENTE', 'PSICOLOGO', 'PSIQUIATRA'));

CREATE DOMAIN dm_status_sessao AS VARCHAR(20)
CHECK (VALUE IN ('AGENDADO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO'));

CREATE DOMAIN dm_conselho AS VARCHAR(20)
CHECK (VALUE IN ('CRP', 'CRM'));

CREATE TABLE usuario (
	id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(255) NOT NULL,
	nome varchar(150) NOT NULL,
	telefone varchar(20) NOT NULL,
	cpf varchar(11) NOT NULL,
	usuario_role dm_role NOT NULL,
	senha varchar(255),
	codigo varchar(6),
	ativo boolean DEFAULT FALSE NOT NULL
);

-- CREATE TABLE profissional (
-- 	id_profissional integer NOT NULL,
-- );
